/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReachRouteImport } from './routes/reach'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminCampaignsRouteImport } from './routes/admin/campaigns'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminHrRouteImport } from './routes/admin/hr'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOperationsRouteImport } from './routes/admin/operations'
import { Route as AdminProcessingRouteImport } from './routes/admin/processing'
import { Route as ApiCommunicationsRouteImport } from './routes/api/communications'
import { Route as ApiMaintenanceRouteImport } from './routes/api/maintenance'
import { Route as ApiReedSyncRouteImport } from './routes/api/reed-sync'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppConsultationsRouteImport } from './routes/app/consultations'
import { Route as AppDiscoverRouteImport } from './routes/app/discover'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthSecurityRouteImport } from './routes/auth/security'
import { Route as AdminCandidatesIndexRouteImport } from './routes/admin/candidates/index'
import { Route as AdminFaqIndexRouteImport } from './routes/admin/faq/index'
import { Route as AdminFaqIdRouteImport } from './routes/admin/faq/$id'
import { Route as AdminFaqNewRouteImport } from './routes/admin/faq/new'
import { Route as AdminJobsIndexRouteImport } from './routes/admin/jobs/index'
import { Route as AdminJobsIdRouteImport } from './routes/admin/jobs/$id'
import { Route as AdminJobsNewRouteImport } from './routes/admin/jobs/new'
import { Route as ApiConsultationsIdRouteImport } from './routes/api/consultations/$id'
import { Route as ApiCvIdRouteImport } from './routes/api/cv/$id'
import { Route as ApiOperationsHealthRouteImport } from './routes/api/operations/health'
import { Route as ApiPrivacyExportRouteImport } from './routes/api/privacy/export'
import { Route as AppCandidatesIndexRouteImport } from './routes/app/candidates/index'
import { Route as AppCandidatesIdRouteImport } from './routes/app/candidates/$id'
import { Route as AppHrIndexRouteImport } from './routes/app/hr/index'
import { Route as AppHrAnswerRouteImport } from './routes/app/hr/answer'
import { Route as AppHrHistoryRouteImport } from './routes/app/hr/history'
import { Route as AppHrLibraryRouteImport } from './routes/app/hr/library'
import { Route as AppJobsIndexRouteImport } from './routes/app/jobs/index'
import { Route as AppJobsIdRouteImport } from './routes/app/jobs/$id'
import { Route as ApiAdminExportKindRouteImport } from './routes/api/admin/export/$kind'
import { Route as ApiCalendarCallbackProviderRouteImport } from './routes/api/calendar/callback/$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReachRoute = ReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHrRoute = AdminHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessingRoute = AdminProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCommunicationsRoute = ApiCommunicationsRouteImport.update({
  id: '/api/communications',
  path: '/api/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaintenanceRoute = ApiMaintenanceRouteImport.update({
  id: '/api/maintenance',
  path: '/api/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReedSyncRoute = ApiReedSyncRouteImport.update({
  id: '/api/reed-sync',
  path: '/api/reed-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationsRoute = AppConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSecurityRoute = AuthSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthRoute,
} as any)
const AdminCandidatesIndexRoute = AdminCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqIndexRoute = AdminFaqIndexRouteImport.update({
  id: '/faq/',
  path: '/faq/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqIdRoute = AdminFaqIdRouteImport.update({
  id: '/faq/$id',
  path: '/faq/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqNewRoute = AdminFaqNewRouteImport.update({
  id: '/faq/new',
  path: '/faq/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIndexRoute = AdminJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsIdRoute = AdminJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsNewRoute = AdminJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AdminRoute,
} as any)
const ApiConsultationsIdRoute = ApiConsultationsIdRouteImport.update({
  id: '/api/consultations/$id',
  path: '/api/consultations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvIdRoute = ApiCvIdRouteImport.update({
  id: '/api/cv/$id',
  path: '/api/cv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsHealthRoute = ApiOperationsHealthRouteImport.update({
  id: '/api/operations/health',
  path: '/api/operations/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivacyExportRoute = ApiPrivacyExportRouteImport.update({
  id: '/api/privacy/export',
  path: '/api/privacy/export',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCandidatesIndexRoute = AppCandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrAnswerRoute = AppHrAnswerRouteImport.update({
  id: '/hr/answer',
  path: '/hr/answer',
  getParentRoute: () => AppRoute,
} as any)
const AppHrHistoryRoute = AppHrHistoryRouteImport.update({
  id: '/hr/history',
  path: '/hr/history',
  getParentRoute: () => AppRoute,
} as any)
const AppHrLibraryRoute = AppHrLibraryRouteImport.update({
  id: '/hr/library',
  path: '/hr/library',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIdRoute = AppJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminExportKindRoute = ApiAdminExportKindRouteImport.update({
  id: '/api/admin/export/$kind',
  path: '/api/admin/export/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarCallbackProviderRoute =
  ApiCalendarCallbackProviderRouteImport.update({
    id: '/api/calendar/callback/$provider',
    path: '/api/calendar/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/reed-sync': typeof ApiReedSyncRoute
  '/app/activity': typeof AppActivityRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/security': typeof AuthSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/faq/$id': typeof AdminFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/api/consultations/$id': typeof ApiConsultationsIdRoute
  '/api/cv/$id': typeof ApiCvIdRoute
  '/api/operations/health': typeof ApiOperationsHealthRoute
  '/api/privacy/export': typeof ApiPrivacyExportRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/hr/answer': typeof AppHrAnswerRoute
  '/app/hr/history': typeof AppHrHistoryRoute
  '/app/hr/library': typeof AppHrLibraryRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/faq/': typeof AdminFaqIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/api/admin/export/$kind': typeof ApiAdminExportKindRoute
  '/api/calendar/callback/$provider': typeof ApiCalendarCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approach': typeof ApproachRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/reed-sync': typeof ApiReedSyncRoute
  '/app/activity': typeof AppActivityRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/security': typeof AuthSecurityRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/faq/$id': typeof AdminFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/api/consultations/$id': typeof ApiConsultationsIdRoute
  '/api/cv/$id': typeof ApiCvIdRoute
  '/api/operations/health': typeof ApiOperationsHealthRoute
  '/api/privacy/export': typeof ApiPrivacyExportRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/hr/answer': typeof AppHrAnswerRoute
  '/app/hr/history': typeof AppHrHistoryRoute
  '/app/hr/library': typeof AppHrLibraryRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/admin/candidates': typeof AdminCandidatesIndexRoute
  '/admin/faq': typeof AdminFaqIndexRoute
  '/admin/jobs': typeof AdminJobsIndexRoute
  '/app/candidates': typeof AppCandidatesIndexRoute
  '/app/hr': typeof AppHrIndexRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/api/admin/export/$kind': typeof ApiAdminExportKindRoute
  '/api/calendar/callback/$provider': typeof ApiCalendarCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/approach': typeof ApproachRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/reach': typeof ReachRoute
  '/sectors': typeof SectorsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/hr': typeof AdminHrRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/processing': typeof AdminProcessingRoute
  '/api/communications': typeof ApiCommunicationsRoute
  '/api/maintenance': typeof ApiMaintenanceRoute
  '/api/reed-sync': typeof ApiReedSyncRoute
  '/app/activity': typeof AppActivityRoute
  '/app/consultations': typeof AppConsultationsRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/profile': typeof AppProfileRoute
  '/app/upload': typeof AppUploadRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/security': typeof AuthSecurityRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/faq/$id': typeof AdminFaqIdRoute
  '/admin/faq/new': typeof AdminFaqNewRoute
  '/admin/jobs/$id': typeof AdminJobsIdRoute
  '/admin/jobs/new': typeof AdminJobsNewRoute
  '/api/consultations/$id': typeof ApiConsultationsIdRoute
  '/api/cv/$id': typeof ApiCvIdRoute
  '/api/operations/health': typeof ApiOperationsHealthRoute
  '/api/privacy/export': typeof ApiPrivacyExportRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/hr/answer': typeof AppHrAnswerRoute
  '/app/hr/history': typeof AppHrHistoryRoute
  '/app/hr/library': typeof AppHrLibraryRoute
  '/app/jobs/$id': typeof AppJobsIdRoute
  '/admin/candidates/': typeof AdminCandidatesIndexRoute
  '/admin/faq/': typeof AdminFaqIndexRoute
  '/admin/jobs/': typeof AdminJobsIndexRoute
  '/app/candidates/': typeof AppCandidatesIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/api/admin/export/$kind': typeof ApiAdminExportKindRoute
  '/api/calendar/callback/$provider': typeof ApiCalendarCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/approach'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/reach'
    | '/sectors'
    | '/services'
    | '/terms'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/campaigns'
    | '/admin/enquiries'
    | '/admin/hr'
    | '/admin/login'
    | '/admin/operations'
    | '/admin/processing'
    | '/api/communications'
    | '/api/maintenance'
    | '/api/reed-sync'
    | '/app/activity'
    | '/app/consultations'
    | '/app/discover'
    | '/app/messages'
    | '/app/profile'
    | '/app/upload'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/security'
    | '/admin/'
    | '/app/'
    | '/admin/faq/$id'
    | '/admin/faq/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/api/consultations/$id'
    | '/api/cv/$id'
    | '/api/operations/health'
    | '/api/privacy/export'
    | '/app/candidates/$id'
    | '/app/hr/answer'
    | '/app/hr/history'
    | '/app/hr/library'
    | '/app/jobs/$id'
    | '/admin/candidates/'
    | '/admin/faq/'
    | '/admin/jobs/'
    | '/app/candidates/'
    | '/app/hr/'
    | '/app/jobs/'
    | '/api/admin/export/$kind'
    | '/api/calendar/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approach'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/reach'
    | '/sectors'
    | '/services'
    | '/terms'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/campaigns'
    | '/admin/enquiries'
    | '/admin/hr'
    | '/admin/login'
    | '/admin/operations'
    | '/admin/processing'
    | '/api/communications'
    | '/api/maintenance'
    | '/api/reed-sync'
    | '/app/activity'
    | '/app/consultations'
    | '/app/discover'
    | '/app/messages'
    | '/app/profile'
    | '/app/upload'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/security'
    | '/admin'
    | '/app'
    | '/admin/faq/$id'
    | '/admin/faq/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/api/consultations/$id'
    | '/api/cv/$id'
    | '/api/operations/health'
    | '/api/privacy/export'
    | '/app/candidates/$id'
    | '/app/hr/answer'
    | '/app/hr/history'
    | '/app/hr/library'
    | '/app/jobs/$id'
    | '/admin/candidates'
    | '/admin/faq'
    | '/admin/jobs'
    | '/app/candidates'
    | '/app/hr'
    | '/app/jobs'
    | '/api/admin/export/$kind'
    | '/api/calendar/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/approach'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/reach'
    | '/sectors'
    | '/services'
    | '/terms'
    | '/unsubscribe'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/campaigns'
    | '/admin/enquiries'
    | '/admin/hr'
    | '/admin/login'
    | '/admin/operations'
    | '/admin/processing'
    | '/api/communications'
    | '/api/maintenance'
    | '/api/reed-sync'
    | '/app/activity'
    | '/app/consultations'
    | '/app/discover'
    | '/app/messages'
    | '/app/profile'
    | '/app/upload'
    | '/auth/callback'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset'
    | '/auth/security'
    | '/admin/'
    | '/app/'
    | '/admin/faq/$id'
    | '/admin/faq/new'
    | '/admin/jobs/$id'
    | '/admin/jobs/new'
    | '/api/consultations/$id'
    | '/api/cv/$id'
    | '/api/operations/health'
    | '/api/privacy/export'
    | '/app/candidates/$id'
    | '/app/hr/answer'
    | '/app/hr/history'
    | '/app/hr/library'
    | '/app/jobs/$id'
    | '/admin/candidates/'
    | '/admin/faq/'
    | '/admin/jobs/'
    | '/app/candidates/'
    | '/app/hr/'
    | '/app/jobs/'
    | '/api/admin/export/$kind'
    | '/api/calendar/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ApproachRoute: typeof ApproachRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ReachRoute: typeof ReachRoute
  SectorsRoute: typeof SectorsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ApiCommunicationsRoute: typeof ApiCommunicationsRoute
  ApiMaintenanceRoute: typeof ApiMaintenanceRoute
  ApiReedSyncRoute: typeof ApiReedSyncRoute
  ApiConsultationsIdRoute: typeof ApiConsultationsIdRoute
  ApiCvIdRoute: typeof ApiCvIdRoute
  ApiOperationsHealthRoute: typeof ApiOperationsHealthRoute
  ApiPrivacyExportRoute: typeof ApiPrivacyExportRoute
  ApiAdminExportKindRoute: typeof ApiAdminExportKindRoute
  ApiCalendarCallbackProviderRoute: typeof ApiCalendarCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reach': {
      id: '/reach'
      path: '/reach'
      fullPath: '/reach'
      preLoaderRoute: typeof ReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hr': {
      id: '/admin/hr'
      path: '/hr'
      fullPath: '/admin/hr'
      preLoaderRoute: typeof AdminHrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processing': {
      id: '/admin/processing'
      path: '/processing'
      fullPath: '/admin/processing'
      preLoaderRoute: typeof AdminProcessingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/communications': {
      id: '/api/communications'
      path: '/api/communications'
      fullPath: '/api/communications'
      preLoaderRoute: typeof ApiCommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maintenance': {
      id: '/api/maintenance'
      path: '/api/maintenance'
      fullPath: '/api/maintenance'
      preLoaderRoute: typeof ApiMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reed-sync': {
      id: '/api/reed-sync'
      path: '/api/reed-sync'
      fullPath: '/api/reed-sync'
      preLoaderRoute: typeof ApiReedSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consultations': {
      id: '/app/consultations'
      path: '/consultations'
      fullPath: '/app/consultations'
      preLoaderRoute: typeof AppConsultationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/security': {
      id: '/auth/security'
      path: '/security'
      fullPath: '/auth/security'
      preLoaderRoute: typeof AuthSecurityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/candidates/': {
      id: '/admin/candidates/'
      path: '/candidates'
      fullPath: '/admin/candidates/'
      preLoaderRoute: typeof AdminCandidatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq/': {
      id: '/admin/faq/'
      path: '/faq'
      fullPath: '/admin/faq/'
      preLoaderRoute: typeof AdminFaqIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq/$id': {
      id: '/admin/faq/$id'
      path: '/faq/$id'
      fullPath: '/admin/faq/$id'
      preLoaderRoute: typeof AdminFaqIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq/new': {
      id: '/admin/faq/new'
      path: '/faq/new'
      fullPath: '/admin/faq/new'
      preLoaderRoute: typeof AdminFaqNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/': {
      id: '/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AdminJobsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/$id': {
      id: '/admin/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AdminJobsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs/new': {
      id: '/admin/jobs/new'
      path: '/jobs/new'
      fullPath: '/admin/jobs/new'
      preLoaderRoute: typeof AdminJobsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/consultations/$id': {
      id: '/api/consultations/$id'
      path: '/api/consultations/$id'
      fullPath: '/api/consultations/$id'
      preLoaderRoute: typeof ApiConsultationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv/$id': {
      id: '/api/cv/$id'
      path: '/api/cv/$id'
      fullPath: '/api/cv/$id'
      preLoaderRoute: typeof ApiCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/health': {
      id: '/api/operations/health'
      path: '/api/operations/health'
      fullPath: '/api/operations/health'
      preLoaderRoute: typeof ApiOperationsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/privacy/export': {
      id: '/api/privacy/export'
      path: '/api/privacy/export'
      fullPath: '/api/privacy/export'
      preLoaderRoute: typeof ApiPrivacyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/candidates/': {
      id: '/app/candidates/'
      path: '/candidates'
      fullPath: '/app/candidates/'
      preLoaderRoute: typeof AppCandidatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/$id': {
      id: '/app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/app/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/': {
      id: '/app/hr/'
      path: '/hr'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/answer': {
      id: '/app/hr/answer'
      path: '/hr/answer'
      fullPath: '/app/hr/answer'
      preLoaderRoute: typeof AppHrAnswerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/history': {
      id: '/app/hr/history'
      path: '/hr/history'
      fullPath: '/app/hr/history'
      preLoaderRoute: typeof AppHrHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/library': {
      id: '/app/hr/library'
      path: '/hr/library'
      fullPath: '/app/hr/library'
      preLoaderRoute: typeof AppHrLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/jobs'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs/$id': {
      id: '/app/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/app/jobs/$id'
      preLoaderRoute: typeof AppJobsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin/export/$kind': {
      id: '/api/admin/export/$kind'
      path: '/api/admin/export/$kind'
      fullPath: '/api/admin/export/$kind'
      preLoaderRoute: typeof ApiAdminExportKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/callback/$provider': {
      id: '/api/calendar/callback/$provider'
      path: '/api/calendar/callback/$provider'
      fullPath: '/api/calendar/callback/$provider'
      preLoaderRoute: typeof ApiCalendarCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminHrRoute: typeof AdminHrRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminProcessingRoute: typeof AdminProcessingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFaqIdRoute: typeof AdminFaqIdRoute
  AdminFaqNewRoute: typeof AdminFaqNewRoute
  AdminJobsIdRoute: typeof AdminJobsIdRoute
  AdminJobsNewRoute: typeof AdminJobsNewRoute
  AdminCandidatesIndexRoute: typeof AdminCandidatesIndexRoute
  AdminFaqIndexRoute: typeof AdminFaqIndexRoute
  AdminJobsIndexRoute: typeof AdminJobsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminHrRoute: AdminHrRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminProcessingRoute: AdminProcessingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFaqIdRoute: AdminFaqIdRoute,
  AdminFaqNewRoute: AdminFaqNewRoute,
  AdminJobsIdRoute: AdminJobsIdRoute,
  AdminJobsNewRoute: AdminJobsNewRoute,
  AdminCandidatesIndexRoute: AdminCandidatesIndexRoute,
  AdminFaqIndexRoute: AdminFaqIndexRoute,
  AdminJobsIndexRoute: AdminJobsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppConsultationsRoute: typeof AppConsultationsRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUploadRoute: typeof AppUploadRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppHrAnswerRoute: typeof AppHrAnswerRoute
  AppHrHistoryRoute: typeof AppHrHistoryRoute
  AppHrLibraryRoute: typeof AppHrLibraryRoute
  AppJobsIdRoute: typeof AppJobsIdRoute
  AppCandidatesIndexRoute: typeof AppCandidatesIndexRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppConsultationsRoute: AppConsultationsRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppProfileRoute: AppProfileRoute,
  AppUploadRoute: AppUploadRoute,
  AppIndexRoute: AppIndexRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppHrAnswerRoute: AppHrAnswerRoute,
  AppHrHistoryRoute: AppHrHistoryRoute,
  AppHrLibraryRoute: AppHrLibraryRoute,
  AppJobsIdRoute: AppJobsIdRoute,
  AppCandidatesIndexRoute: AppCandidatesIndexRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSecurityRoute: typeof AuthSecurityRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSecurityRoute: AuthSecurityRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ApproachRoute: ApproachRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ReachRoute: ReachRoute,
  SectorsRoute: SectorsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ApiCommunicationsRoute: ApiCommunicationsRoute,
  ApiMaintenanceRoute: ApiMaintenanceRoute,
  ApiReedSyncRoute: ApiReedSyncRoute,
  ApiConsultationsIdRoute: ApiConsultationsIdRoute,
  ApiCvIdRoute: ApiCvIdRoute,
  ApiOperationsHealthRoute: ApiOperationsHealthRoute,
  ApiPrivacyExportRoute: ApiPrivacyExportRoute,
  ApiAdminExportKindRoute: ApiAdminExportKindRoute,
  ApiCalendarCallbackProviderRoute: ApiCalendarCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
